version: "{build}"

environment:
  matrix:
    - nodejs_version: "" # latest

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
